---
# tasks file for default-tooling

- name: Install default packages
  dnf: 
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages | map(attribute='dnf') | list }}"
    - "{{ extend_packages | map(attribute='dnf') | list }}"
  tags:
    - dnf
    - download
    - packages
  become: true
