---
# tasks file for default-tooling

- name: Install default packages
  dnf: 
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages | map(attribute='apt') | list }}"
  become: true
