---
# tasks file for rpmfusion

- name: Add RPMFusion GPG key
  rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=view&target=RPM-GPG-KEY-rpmfusion-free-fedora-26
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_major_version == 26


- name: Install RPMFusion
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  when:
    - ansible_distribution == "Fedora"
  become: true
