---
# tasks file for vscode
#

- name: Downgrade urllib3 to 1.13.1
  pip: 
    name: urllib3
    version: 1.13.1
  tags:
    - vscode
    - pip
    - libs
  become: true

- name: Import GPG key
  rpm_key:
    state: present
    key: "https://packages.microsoft.com/keys/microsoft.asc"
  tags:
    - vscode
    - dnf
    - gpg-key
    - download

- name: Add official repository
  yum_repository:
    state: present
    name: vscode
    description: Official repository for VSCode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  tags:
    - vscode
    - dnf
    - gpg-key
  become: true

- name: Install vscode
  dnf:
    name: code
    state: present
  tags:
    - vscode
    - dnf
    - packages
  become: true
