---
# handlers file for gitkraken

- name: Update icon directory timestamp
  file:
    path: "/usr/share/icons/hicolor"
    state: touch
  tags:
    - gitkraken
    - gtk
  become: true

- name: Update GTK icon cache
  tags:
    - gitkraken
    - gtk
  command: "gtk-update-icon-cache"
