---
# handlers file for automated-updates

- name: restart dnf-automatic
  service:
    name: dnf-automatic.timer
    state: restarted
    enabled: yes
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_major_version > 21
    - ansible_virtualization_type != "docker"
  become: true
