---
# tasks file for atom

- name: Check atom is installed
  atom:
    name: atom
    state: present
  ignore_errors: true
  register: atom_installed
  tags:
    - atom
    - apt
    - packages
  become: true

- name: Download atom
  get_url:
    url: "{{ atom_url.deb }}"
    dest: "/tmp/atom.deb"
  register: atom_download
  tags:
    - atom
    - download
    - packages
  when:
    - atom_installed|failed

- name: Install atom
  apt:
    deb: "/tmp/atom.deb"
    state: present
  tags:
    - atom
    - apt
    - packages
  become: true
  ignore_errors: true
  when:
    - atom_installed|failed
    - atom_download|succeeded

- name: Install atom dependencies (very hacky)
  command: "apt-get install -f"
  become: true
  when:
    - atom_installed|failed
    - atom_downloaded|succeeded

- name: Clean up
  file:
    path: "/tmp/atom.deb"
    state: absent
  tags:
    - atom

- name: Install Nautilus-Extension
  copy:
    src: open-atom.py
    dest: /usr/share/nautilus-python/extensions/open-atom.py
  tags:
    - atom
    - python
    - nautilus
    - nautilus-python
    - nautlius-python-extension
  become: true
  notify: "Nautilus python extension notification"
